application: gdgcluj-github-demo
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /first-steps-into/github/(.*\.(htm|html|css|js))$
  static_files: github/\1
- url: /first-steps-into/github/
  script: github/index.html

