application: first-steps-into
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /github/
  script: /github/index.html
- url: /github
  static_dir: github
- url: /impress.js
  static_dir: impress.js
- url: /impress.js
  static_dir: impress.js